name: GoogleTest

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: dependencies
        run: |
          sudo apt install -y cmake
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: '0'
      - name: build
        run: |
          cmake -B build .
          cmake --build build -j
      - name: test
        run: ./build/test
