name: GoogleTest

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake libvulkan1 libglfw3-dev glslang-dev glslang-tools libfmt-dev
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: '0'
      - name: dump
        run: |
          ls /usr/include/ | grep glslang
          ls /usr/include/glslang
          ls /usr/lib/cmake/gl*
          ls /usr/lib/libglslang*
      - name: build
        run: |
          cmake -B build .
          cmake --build build -j
      - name: test
        run: ./build/test
