name: GoogleTest

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-24.04

    defaults:
      run:
        shell: bash

    steps:
      - name: dependencies
        run: |
          sudo apt update -y
          sudo apt install -y cmake libvulkan1 libglfw3-dev \
            glslang-tools glslang-dev libfmt-dev gcc-14 libgccjit-14-dev
          sudo ln -s /usr/lib/gcc/x86_64-linux-gnu/14/include/libgccjit.h /usr/include/libgccjit.h
          sudo ln -s /usr/lib/gcc/x86_64-linux-gnu/14/libgccjit.so /usr/lib/libgccjit.so
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: '0'
      - name: build
        run: |
          cmake -B build .
          cmake --build build -j -t test
      - name: test
        run: ./build/test
